### ISSUE TITLE
process() method is deprecated

### ISSUE THREAD

**Issue by pburtchaell** [passy/autoprefixer-loader#20]
When I use the loader, I get:  `Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead`.

**Comment by andrew-d** [comment]
:+1: - I just ran into this too - see https://twitter.com/autoprefixer/status/599626778995531776

**Comment by myagoo** [comment]
+1

**Comment by whoknows** [comment]
+1

**Comment by unindented** [comment]
:+1:

**Comment by pburtchaell** [comment]
> 1. Use postcss-loader instead of depreacted autoprefixer-loader 
> — [From this tweet](https://twitter.com/andreysitnik/status/603838778885730304)

**Comment by cesarandreu** [comment]
+1

**Comment by passy** [comment]
I've opened a PR on #20. Could some of you +1'ers verify that this works for you? :)

**Comment by daviferreira** [comment]
@passy worked for me, thanks :)

**Comment by passy** [comment]
@daviferreira Thanks for testing!

**Comment by myagoo** [comment]
Fixed for me too, thank you

**Comment by pburtchaell** [comment]
@passy Thanks for the quick fix. :)
