### ISSUE TITLE
Update autoprefixer

### ISSUE THREAD

**Issue by danieljuhl** [passy/autoprefixer-loader#27]
To get rid of deprecated warnings from PostCSS, and to use autoprefixer instead of autoprefixer-core.

**Comment by vn38minhtran** [comment]
+1

Warning message:
```
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
```

**Comment by passy** [comment]
PR welcome. :)

**Comment by ai** [comment]
@passy PR to update Autoprefixer? O_o Update packages is work of package maintainer.

**Comment by passy** [comment]
@ai The job of the maintainer is to stay up to date with the issue tracker, merge PRs and cut new releases. Everything beyond that is contribution, not maintenance. I wish I had the time to not limit myself to one of them, but that's simply not realistic for me at the moment.

**Comment by grabbou** [comment]
PR with updated dependencies submitted.

**Comment by passy** [comment]
Merged and published as 3.0. Thanks again for the help!

**Comment by isellsoap** [comment]
Note the `and to use autoprefixer instead of autoprefixer-core` from the first comment. That wasn’t done. :-)

Console outputs this:
```
autoprefixer-core was deprecated. Use autoprefixer package.
```

**Comment by deepsweet** [comment]
still have

```
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
```

with v3.1.0
