### ISSUE TITLE
Shouldn't autoprefixer and postcss be peerDependencies?

### ISSUE THREAD

**Issue by mik01aj** [passy/autoprefixer-loader#33]
Currently your [`package.json`](https://github.com/passy/autoprefixer-loader/blob/master/package.json) has:

```
"dependencies": {
    "autoprefixer": "^6.0.2",
    "loader-utils": "^0.2.11",
    "postcss": "^5.0.4",
    "postcss-safe-parser": "^1.0.1"
  },
```

I think it would be better to put them into `peerDependencies`, so that `autoprefixer-loader` users could use any versions they need. [Sass-loader does it this way](https://www.npmjs.com/package/sass-loader).

Btw, if you have `postcss-safe-parser`, do you still need `postcss` dependency? ( `postcss-safe-parser` depends on `postcss`, so with npm@2 it gets installed twice.)

**Comment by mik01aj** [comment]
Btw. There is [`postcss-loader`](https://github.com/postcss/postcss-loader), so maybe this whole module could be deprecated.

**Comment by ai** [comment]
Yeap, Autoprefixer official way is to use only `postcss-loader`.
