### ISSUE TITLE
Deprecation warning with Webpack 2+

### ISSUE THREAD

**Issue by AndrewRayCode** [passy/autoprefixer-loader#38]
> (node:45058) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

From this line:

```
var params = loaderUtils.parseQuery(this.query);
```

When using a valid object query:
```
{
    loader: 'autoprefixer-loader',
    options: { browser: 'last 2 version'
}
```

**Comment by ai** [comment]
`autoprefixer-loader` is deprecated. Please use `postcss-loader` with Autoprefixer plugin.
